title: BTI Multimedia
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.75
  brandStrength: 0.3680851
  lightness: 0.7404255
  brandColors:
    - '#FFFFFF'
    - '#20391C'
    - '#716E65'
    - '#79AC61'
    - '#C4C5BF'
  rhythmicContrast: 0.9808511
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: BTI Multimedia
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.22568
layout_spectrum: 0
